import Menu from "@/components/Menu";
import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const myFont = localFont({ src: './fonts/TT Hoves Pro Trial Medium.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      
      <body className="overflow-hidden">
        <Menu />
        {children}
      </body>
    </html>
  );
}
